// Generated by CoffeeScript 1.6.3
(function() {
  var Linda, linda;

  Linda = require("./client");

  linda = new Linda("linda.masuilab.org:10010", "takumibaba");

  linda.on("connect", function() {
    linda.ts.write([0, 1, 2]);
    return linda.ts.read([0, 1, 2], function(tuple, info) {
      return console.log(tuple, info);
    });
  });

}).call(this);
