// Generated by CoffeeScript 1.6.3
(function() {
  var Linda, linda;

  Linda = require("./client");

  linda = new Linda("http://linda.masuilab.org", "takumibaba");

  linda.io.on("connect", function() {
    linda.ts.watch([0, 1], function(tuple, info) {
      console.log("watch!");
      return console.log(tuple, info);
    });
    linda.ts.write([0, 1, 2]);
    linda.ts.read([0, 1, 2], function(tuple, info) {
      console.log("read!");
      return console.log(tuple, info);
    });
    linda.ts.write([0, 1, 2, 3]);
    return linda.ts.take([0, 1, 2], function(tuple, info) {
      console.log("take!");
      return console.log(tuple, info);
    });
  });

}).call(this);
